import type { Metadata } from 'next';
import './globals.css';
import Background from '@/components/Background';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Background />
        <Header />
        {children}
      </body>
    </html>
  );
}
