import type { Metadata } from 'next';
import '../globals.css';
import Background from '@/components/warframe/Background';
import Header from '@/components/warframe/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Background />
      <Header />
      {children}
    </>
  );
}
