# Warframe Tracker
API_URL = '/warframe/api'
SESSION_KEY_LENGTH = 64

WARFRAMES = {
    "atlas": "Атлас",
    "banshee": "Банши",
    "baruuk": "Баруук",
    "valkyr": "Валькирия",
    "wisp": "Висп", 
    "vauban": "Вобан",
    "volt": "Вольт",
    "voruna": "Воруна",
    "wukong": "Вуконг",
    "gara": "Гара",
    "garuda": "Гаруда",
    "gauss": "Гаусс",
    "hydroid": "Гидроид",
    "grendel": "Грендель",
    "dagath": "Дагас",
    "dante": "Данте",
    "gyre": "Джайра",
    "jade": "Джейд",
    "xaku": "Заку",
    "zephyr": "Зефир",
    "ivara": "Ивара",
    "inaros": "Инарас",
    "caliban": "Калибан",
    "koumei": "Комея",
    "khora": "Кора",
    "qorvex": "Корвекс",
    "kullervo": "Куллерво",
    "lavos": "Лавос",
    "limbo": "Лимбо",
    "loki": "Локи",
    "mirage": "Мираж",
    "mesa": "Миса",
    "mag": "Мэг",
    "nekros": "Некрос",
    "nidus": "Нидус",
    "nyx": "Никс",
    "nova": "Nova",
    "nezha": "Нэчжа",
    "oberon": "Оберон",
    "octavia": "Октавия",
    "protea": "Протея",
    "revenant": "Ревенант",
    "rhino": "Рино",
    "saryn": "Сарина",
    "sevagoth": "Севагот",
    "styanax": "Стинакс",
    "titania": "Титания",
    "trinity": "Тринити",
    "frost": "Фрост",
    "harrow": "Харроу",
    "hildryn": "Хильдрин",
    "chroma": "Хрома",
    "cyte-09": "Цит-09",
    "citrine": "Цитрина",
    "equinox": "Эквинокс",
    "excalibur": "Экскалибур",
    "ember": "Эмбер",
    "ash": "Эш",
    "yareli": "Ярели"
}

NOT_PRIME = [
    "voruna", "dagath", "dante", "gyre", "jade", "caliban", "koumei", "qorvex", "kullervo", "styanax", "cyte-09", "citrine", "yareli"
]